SAMPLE_DATA = [{'01ed8c9': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': '01ed8c9.png',
              'title': 'Introducing iOS Design Patterns in Swift – Part '
                       '2/2 - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/90773/introducing-ios-design-patterns-in-swift-part-2'},
  '06743cb': {'is_public': False,
              'tags': ['OpenGL', 'iOS'],
              'thumb': '06743cb.png',
              'title': 'OpenGL ES Pixel Shaders Tutorial - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/70208/opengl-es-pixel-shaders-tutorial'},
  '0bedfeb': {'is_public': False,
              'tags': ['Machine-Learning'],
              'thumb': '0bedfeb.png',
              'title': 'Getting Started with Machine Learning | Javalobby',
              'url': 'http://java.dzone.com/articles/getting-started-machine'},
  '106ecf3': {'is_public': True,
              'tags': ['BigData'],
              'thumb': '106ecf3.png',
              'title': 'Apache Spark™ - Lightning-Fast Cluster Computing',
              'url': 'https://spark.apache.org'},
  '13a20c6': {'is_public': False,
              'tags': ['Swift'],
              'thumb': '13a20c6.png',
              'title': 'Grand Central Dispatch Tutorial for Swift: Part '
                       '2/2 - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/79150/grand-central-dispatch-tutorial-swift-part-2'},
  '161b40a': {'is_public': False,
              'tags': ['Machine-Learning'],
              'thumb': '161b40a.png',
              'title': 'Test Run - L1 and L2 Regularization for Machine '
                       'Learning',
              'url': 'https://msdn.microsoft.com/en-us/magazine/dn904675.aspx'},
  '163175e': {'is_public': False,
              'tags': ['Programming'],
              'thumb': '163175e.png',
              'title': 'Adaptive Batch Sizes for Backend Processing',
              'url': 'http://jeffhandley.com/archive/2014/12/16/Adaptive-Batch-Sizes-for-Backend-Processing.aspx'},
  '1751d9e': {'is_public': False,
              'tags': ['Deep-Learning'],
              'thumb': '1751d9e.png',
              'title': 'NVIDIA CES 2015 press conference: DRIVE PX '
                       'Computer Vision (part 7) - YouTube',
              'url': 'https://www.youtube.com/watch?v=zsVsUvx8ieo'},
  '1cfd6cf': {'is_public': False,
              'tags': ['OpenGL'],
              'thumb': '1cfd6cf.png',
              'title': 'Code And Graphics: Flexible particle system - '
                       'Updaters',
              'url': 'http://www.bfilipek.com/2014/06/flexible-particle-system-updaters.html'},
  '21ba866': {'is_public': False,
              'tags': ['C#', '.Net'],
              'thumb': '21ba866.png',
              'title': 'Graphs and pathing in C#',
              'url': 'http://www.arakawa.asia/2013/08/04/'},
  '24e3a6c': {'is_public': False,
              'tags': ['e-Books'],
              'thumb': '24e3a6c.png',
              'title': '10 Free Books for Learning JavaScript | Developers '
                       'Lane',
              'url': 'http://www.developerslane.com/10-free-books-for-learning-javascript/'},
  '25cb594': {'is_public': False,
              'tags': ['Swift'],
              'thumb': '25cb594.png',
              'title': 'Exploring KVO alternatives with Swift',
              'url': 'http://www.scottlogic.com/blog/2015/02/11/swift-kvo-alternatives.html'},
  '27679ba': {'is_public': False,
              'tags': ['Swift'],
              'thumb': '27679ba.png',
              'title': 'Swift Functional Programming Tutorial - Ray '
                       'Wenderlich',
              'url': 'http://www.raywenderlich.com/82599/swift-functional-programming-tutorial'},
  '2ec35fb': {'is_public': False,
              'tags': ['NodeJs', 'e-Books'],
              'thumb': '2ec35fb.png',
              'title': '6 Best Free Node.js Ebooks | TheNeoDesign.com',
              'url': 'http://theneodesign.com/best-free-node-js-ebooks/'},
  '392b5e2': {'is_public': False,
              'tags': ['Swift'],
              'thumb': '392b5e2.png',
              'title': 'Core Data And Swift « Under The Bridge',
              'url': 'http://www.alexcurylo.com/blog/2014/08/16/core-data-and-swift/'},
  '3dc1101': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': '3dc1101.png',
              'title': 'Storyboards Tutorial in Swift: Part 2 - Ray '
                       'Wenderlich',
              'url': 'http://www.raywenderlich.com/81880/storyboards-tutorial-swift-part-2'},
  '3e6f545': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': '3e6f545.png',
              'title': 'Learn to Code iOS Apps with Swift Tutorial 2: Your '
                       'First Project - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/75919/learn-to-code-ios-apps-with-swift-tutorial-2'},
  '478358b': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': '478358b.png',
              'title': 'Introducing iOS Design Patterns in Swift – Part '
                       '1/2 - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/86477/introducing-ios-design-patterns-in-swift-part-1'},
  '50db3e4': {'is_public': False,
              'tags': ['Swift'],
              'thumb': '50db3e4.png',
              'title': 'Building Your First Swift App Video - Swift Blog - '
                       'Apple Developer',
              'url': 'https://developer.apple.com/swift/blog/?id=16'},
  '558249b': {'is_public': False,
              'tags': ['Git'],
              'thumb': '558249b.png',
              'title': 'Git Tutorial - Git Fu With The Command Line - Ray '
                       'Wenderlich',
              'url': 'http://www.raywenderlich.com/74258/git-tutorial-intermediate'},
  '560b007': {'is_public': False,
              'tags': ['Swift'],
              'thumb': '560b007.png',
              'title': 'Swift Learning Resources - We ❤ Swift',
              'url': 'http://www.weheartswift.com/swift-learning-resources/'},
  '5e7290b': {'is_public': False,
              'tags': ['Machine-Learning'],
              'thumb': '5e7290b.png',
              'title': 'What is Machine Learning? - Machine Learning - '
                       'Site Home - TechNet Blogs',
              'url': 'http://blogs.technet.com/b/machinelearning/archive/2014/07/01/what-is-machine-learning.aspx'},
  '60a46ae': {'is_public': True,
              'tags': ['Js'],
              'thumb': '60a46ae.png',
              'title': 'AngularJS — Superheroic JavaScript MVW Framework',
              'url': 'https://angularjs.org'},
  '61163b6': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': '61163b6.png',
              'title': 'Learn To Code iOS Apps With Swift Tutorial 5: '
                       'Making it Beautiful - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/78264/learn-to-code-ios-apps-with-swift-tutorial-5'},
  '634dca4': {'is_public': False,
              'tags': ['OSX', 'Swift', 'Cocoa'],
              'thumb': '634dca4.png',
              'title': 'Getting Started With OS X and Swift Tutorial: Part '
                       '2/3 - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/87003/getting-started-with-os-x-and-swift-tutorial-part-2'},
  '70dcead': {'is_public': True,
              'tags': ['Js'],
              'thumb': '70dcead.png',
              'title': 'Learn ES6 · 6to5',
              'url': 'http://6to5.org/docs/learn-es6/'},
  '82b46bf': {'is_public': False,
              'tags': ['Swift'],
              'thumb': '82b46bf.png',
              'title': 'Grand Central Dispatch Tutorial for Swift: Part '
                       '1/2 - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/79149/grand-central-dispatch-tutorial-swift-part-1'},
  '909f5d3': {'is_public': False,
              'tags': ['WPF', '.Net'],
              'thumb': '909f5d3.png',
              'title': 'WPF - Build Fault-Tolerant Composite Applications',
              'url': 'https://msdn.microsoft.com/en-us/magazine/dn519924.aspx'},
  '90c0160': {'is_public': False,
              'tags': ['Machine-Learning'],
              'thumb': '90c0160.png',
              'title': 'Math for machine learning - FastML',
              'url': 'http://fastml.com/math-for-machine-learning/'},
  '91e78ee': {'is_public': False,
              'tags': ['OSX', 'Swift', 'Cocoa'],
              'thumb': '91e78ee.png',
              'title': 'Introduction to OS X Tutorial: Core Controls and '
                       'Swift Part 1/2 - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/82046/introduction-to-os-x-tutorial-core-controls-and-swift-part-1'},
  '98707de': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': '98707de.png',
              'title': 'Learn to Code iOS Apps with Swift Tutorial 1: '
                       'Welcome to Programming - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/75601/learn-to-code-ios-apps-with-swift-tutorial-1'},
  'a1eb294': {'is_public': False,
              'tags': ['Machine-Learning', 'Deep-Learning'],
              'thumb': 'a1eb294.png',
              'title': 'Learn some Deep Learning in 2015 | Data Science 101',
              'url': 'http://101.datascience.community/2015/01/07/learn-some-deep-learning-in-2015/'},
  'a48ef25': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': 'a48ef25.png',
              'title': 'Beginning Auto Layout Tutorial in Swift: Part 1/2 '
                       '- Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/83129/beginning-auto-layout-tutorial-swift-part-1'},
  'a7223ec': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': 'a7223ec.png',
              'title': 'Storyboards Tutorial in Swift: Part 1 - Ray '
                       'Wenderlich',
              'url': 'http://www.raywenderlich.com/81879/storyboards-tutorial-swift-part-1'},
  'a8b4cd2': {'is_public': True,
              'tags': ['Swift'],
              'thumb': 'a8b4cd2.png',
              'title': 'Swift - objc.io',
              'url': 'http://www.objc.io/issue-16/'},
  'ac3632c': {'is_public': False,
              'tags': ['Js'],
              'thumb': 'ac3632c.png',
              'title': 'Angular directives for Bootstrap',
              'url': 'http://angular-ui.github.io/bootstrap/'},
  'bc5667c': {'is_public': False,
              'tags': ['BigData'],
              'thumb': 'bc5667c.png',
              'title': "Introducing DZone's 2014 Guide to Big Data | "
                       'Javalobby',
              'url': 'http://java.dzone.com/articles/introducing-dzones-2014-guide-2'},
  'bdaf43b': {'is_public': False,
              'tags': ['BigData', 'Machine-Learning'],
              'thumb': 'bdaf43b.png',
              'title': 'Big Data - Protect Your Online Services with Big '
                       'Data and Machine Learning',
              'url': 'https://msdn.microsoft.com/en-us/magazine/dn890371.aspx'},
  'befdc1d': {'is_public': False,
              'tags': ['OSX', 'Swift', 'Cocoa'],
              'thumb': 'befdc1d.png',
              'title': 'Getting Started With OS X and Swift Tutorial: Part '
                       '3/3 - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/87004/getting-started-with-os-x-and-swift-tutorial-part-3'},
  'c8747d9': {'is_public': False,
              'tags': ['Swift'],
              'thumb': 'c8747d9.png',
              'title': 'how to make http request in swift',
              'url': 'http://blogs.shephertz.com/2014/06/20/making-http-requests-in-swift/'},
  'c936075': {'is_public': False,
              'tags': ['NodeJs'],
              'thumb': 'c936075.png',
              'title': '15 Best Node.js Frameworks For Developers - '
                       'Webdesigncone',
              'url': 'http://webdesigncone.com/2014/node-js-frameworks/'},
  'cc75d98': {'is_public': False,
              'tags': ['Python'],
              'thumb': 'cc75d98.png',
              'title': '10 Myths of Enterprise Python from PayPal | '
                       'Michael Kennedy on Technology',
              'url': 'http://blog.michaelckennedy.net/2014/12/11/10-myths-of-enterprise-python-from-paypal'},
  'd5490ad': {'is_public': False,
              'tags': ['OSX', 'Swift', 'Cocoa'],
              'thumb': 'd5490ad.png',
              'title': 'Getting Started With OS X and Swift Tutorial: Part '
                       '1/3 - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/87002/getting-started-with-os-x-and-swift-tutorial-part-1'},
  'dc6c623': {'is_public': False,
              'tags': ['BigData'],
              'thumb': 'dc6c623.png',
              'title': 'Big Data - Top 6 Frameworks Required to Get '
                       'Started - Bytes Cravings',
              'url': 'http://vitalflux.com/big-data-top-6-tools-frameworks-required-get-started'},
  'e0a833e': {'is_public': False,
              'tags': ['Swift'],
              'thumb': 'e0a833e.png',
              'title': 'Playing with Strings - We ❤ Swift',
              'url': 'http://www.weheartswift.com/playing-strings/'},
  'ec05bb2': {'is_public': False,
              'tags': ['OSX', 'Swift', 'Cocoa'],
              'thumb': 'ec05bb2.png',
              'title': 'Introduction to OS X Tutorial: Core Controls and '
                       'Swift Part 2/2 - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/82047/introduction-to-os-x-tutorial-core-controls-and-swift-part-2'},
  'edfe590': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': 'edfe590.png',
              'title': 'Beginning Auto Layout Tutorial in Swift: Part 2/2 '
                       '- Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/83130/beginning-auto-layout-tutorial-swift-part-2'},
  'f7c145a': {'is_public': False,
              'tags': ['Cpp'],
              'thumb': 'f7c145a.png',
              'title': 'Windows with C++ - DirectComposition: A '
                       'Retained-Mode API to Rule Them All',
              'url': 'https://msdn.microsoft.com/en-us/magazine/dn759437.aspx'},
  'fbf3eb6': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': 'fbf3eb6.png',
              'title': 'Learn to Code iOS Apps with Swift Tutorial 3: '
                       'Arrays, Objects, and Classes - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/76044/learn-to-code-ios-apps-with-swift-tutorial-3'},
  'fe3759b': {'is_public': False,
              'tags': ['Swift', 'iOS'],
              'thumb': 'fe3759b.png',
              'title': 'Learn To Code iOS Apps With Swift Tutorial 4: Your '
                       'First App - Ray Wenderlich',
              'url': 'http://www.raywenderlich.com/77176/learn-to-code-ios-apps-with-swift-tutorial-4'}},
 {'0dd97ea': {'is_public': False,
              'tags': ['Django', 'Python'],
              'thumb': '0dd97ea.png',
              'title': 'Django REST framework',
              'url': 'http://www.django-rest-framework.org'},
  '69bd006': {'is_public': False,
              'tags': ['Python', 'Machine-Learning'],
              'thumb': '69bd006.png',
              'title': 'scikit-image: Image processing in Python — '
                       'scikit-image',
              'url': 'http://scikit-image.org'},
  '7741a9a': {'is_public': True,
              'tags': ['Python'],
              'thumb': '7741a9a.png',
              'title': 'SciPy.org — SciPy.org',
              'url': 'http://www.scipy.org'},
  '80808a3': {'is_public': True,
              'tags': ['Hosting'],
              'thumb': '80808a3.png',
              'title': 'SSD Cloud Server, VPS Server, Simple Cloud Hosting '
                       '| DigitalOcean',
              'url': 'https://www.digitalocean.com'},
  '8509ac0': {'is_public': False,
              'tags': ['Django', 'OAuth'],
              'thumb': '8509ac0.png',
              'title': 'django-allauth',
              'url': 'http://www.intenct.nl/projects/django-allauth'},
  '9a72422': {'is_public': True,
              'tags': ['Hosting'],
              'thumb': '9a72422.png',
              'title': 'AWS | Cloud Website Hosting - Business Website '
                       'Hosting',
              'url': 'http://aws.amazon.com/websites/'},
  '9a85acf': {'is_public': True,
              'tags': ['Python', 'Hosting'],
              'thumb': '9a85acf.png',
              'title': 'Host, run, and code Python in the cloud: '
                       'PythonAnywhere',
              'url': 'https://www.pythonanywhere.com'},
  'b7e79d3': {'is_public': False,
              'tags': ['Python', 'e-Books'],
              'thumb': 'b7e79d3.png',
              'title': 'Dive Into Python 3',
              'url': 'http://www.diveintopython3.net'},
  'd122bf3': {'is_public': True,
              'tags': ['Python'],
              'thumb': 'd122bf3.png',
              'title': 'awesome-python/README.md at master · '
                       'vinta/awesome-python · GitHub',
              'url': 'https://github.com/vinta/awesome-python/blob/master/README.md'},
  'd45c3d4': {'is_public': True,
              'tags': ['Python'],
              'thumb': 'd45c3d4.png',
              'title': 'matplotlib: python plotting — Matplotlib 1.4.2 '
                       'documentation',
              'url': 'http://matplotlib.org'},
  'dc32c2b': {'is_public': False,
              'tags': ['Python', 'Machine-Learning'],
              'thumb': 'dc32c2b.png',
              'title': 'scikit-learn: machine learning in Python — '
                       'scikit-learn 0.15.2 documentation',
              'url': 'http://scikit-learn.org/stable/'},
  'fe6961e': {'is_public': False,
              'tags': ['Django', 'Python'],
              'thumb': 'fe6961e.png',
              'title': 'The Web framework for perfectionists with '
                       'deadlines | Django',
              'url': 'https://www.djangoproject.com'}},
 {'0505d36': {'is_public': True,
              'tags': ['Fashion', 'Watches'],
              'thumb': '0505d36.png',
              'title': 'Men | MVMT Watches',
              'url': 'http://www.mvmtwatches.com/collections/men'},
  '135091c': {'is_public': True,
              'tags': ['Shopping', 'Fashion'],
              'thumb': '135091c.png',
              'title': "Men's Looks | Lookastic for Men",
              'url': 'http://lookastic.com/men'},
  '22f2bc8': {'is_public': True,
              'tags': ['News'],
              'thumb': '22f2bc8.png',
              'title': 'BBC - Homepage',
              'url': 'http://www.bbc.co.uk'},
  '2e14acf': {'is_public': True,
              'tags': ['Cars'],
              'thumb': '2e14acf.png',
              'title': 'Auto Trader UK - New & used cars for sale',
              'url': 'http://www.autotrader.co.uk'},
  '4abd891': {'is_public': True,
              'tags': ['Shopping'],
              'thumb': '4abd891.png',
              'title': 'The Single Malt Whisky Range - Glengoyne Single '
                       'Malt Whisky Distillery Shop',
              'url': 'http://shop.glengoyne.com/whisky-range'},
  '514955e': {'is_public': True,
              'tags': ['News'],
              'thumb': '514955e.png',
              'title': 'The Atlantic — News and analysis on politics, '
                       'business, culture, technology, national, '
                       'international, and life – TheAtlantic.com',
              'url': 'http://www.theatlantic.com'},
  '533c7c6': {'is_public': True,
              'tags': ['Fashion', 'Watches'],
              'thumb': '533c7c6.png',
              'title': 'digital grande : digital grande',
              'url': 'http://www.normaltimepieces.com/en/watches-digital-grande/digital-grande-detail'},
  '5b81db8': {'is_public': True,
              'tags': ['Shopping'],
              'thumb': '5b81db8.png',
              'title': 'Electronics, Cars, Fashion, Collectibles, Coupons '
                       'and More | eBay',
              'url': 'http://www.ebay.co.uk'},
  '699b33d': {'is_public': True,
              'tags': ['Cars'],
              'thumb': '699b33d.png',
              'title': 'BMW BLOG - Your Daily BMW News, Photos, Videos and '
                       'Test Drives',
              'url': 'http://www.bmwblog.com'},
  '6c2d79c': {'is_public': True,
              'tags': ['Free-time'],
              'thumb': '6c2d79c.png',
              'title': '9GAG - Why So Serious?',
              'url': 'http://9gag.com'},
  '8b8d228': {'is_public': True,
              'tags': ['Shopping'],
              'thumb': '8b8d228.png',
              'title': 'Amazon.co.uk: Low Prices in Electronics, Books, '
                       'Sports Equipment & more',
              'url': 'http://www.amazon.co.uk'},
  '97ce4b5': {'is_public': True,
              'tags': ['Free-time'],
              'thumb': '97ce4b5.png',
              'title': 'xkcd: Friendship',
              'url': 'http://xkcd.com'},
  'a8d0016': {'is_public': True,
              'tags': ['Cars'],
              'thumb': 'a8d0016.png',
              'title': 'Quattroworld Independent Audi News, Audi Forums '
                       'and more',
              'url': 'http://www.quattroworld.com'},
  'bc27bd8': {'is_public': True,
              'tags': ['Shopping', 'Sport'],
              'thumb': 'bc27bd8.png',
              'title': 'Glasgow University - Online Store',
              'url': 'http://www.gusportshop.com'},
  'd57adfd': {'is_public': True,
              'tags': ['Shopping', 'Sport'],
              'thumb': 'd57adfd.png',
              'title': 'SportsDirect.com - Trainers, Football Boots, '
                       'Football Shirts, Running Shoes',
              'url': 'http://www.sportsdirect.com'},
  'e05e64a': {'is_public': True,
              'tags': ['Shopping'],
              'thumb': 'e05e64a.png',
              'title': "ASOS | Shop women's fashion & men's clothing | "
                       'Free Delivery & Returns',
              'url': 'http://www.asos.com'},
  'f2b7f99': {'is_public': True,
              'tags': ['News'],
              'thumb': 'f2b7f99.png',
              'title': 'Breaking News, U.S., World, Weather, Entertainment '
                       '& Video News - CNN.com',
              'url': 'http://edition.cnn.com'},
  'ff75ad3': {'is_public': True,
              'tags': ['Cars'],
              'thumb': 'ff75ad3.png',
              'title': 'Top Gear: cars, driving, supercars and the TV show '
                       '- BBC Top Gear - BBC Top Gear',
              'url': 'http://www.topgear.com/uk/'}},
 {'2575a23': {'is_public': True,
              'tags': ['UX'],
              'thumb': '2575a23.png',
              'title': 'A List Apart: For People Who Make Websites',
              'url': 'http://alistapart.com'},
  '3d0c296': {'is_public': True,
              'tags': ['Design', 'Colors'],
              'thumb': '3d0c296.png',
              'title': 'Flat UI Colors',
              'url': 'http://flatuicolors.com/'},
  '44a9be2': {'is_public': True,
              'tags': ['Design'],
              'thumb': '44a9be2.png',
              'title': 'Dribbble - Wayfaring.png by Victor Erixon',
              'url': 'http://dribbble.com/shots/1370174-Wayfaring-App/attachments/196474'},
  '53a8acd': {'is_public': True,
              'tags': ['Design'],
              'thumb': '53a8acd.png',
              'title': 'Principles of Flat Design - Designmodo',
              'url': 'http://designmodo.com/flat-design-principles/'},
  '5b35871': {'is_public': True,
              'tags': ['Design'],
              'thumb': '5b35871.png',
              'title': 'Dribbble - Real_Pixels.jpg by Balraj Chana',
              'url': 'http://dribbble.com/shots/1642582-Socially-Infographical/attachments/257249'},
  '6606c2d': {'is_public': True,
              'tags': ['Design'],
              'thumb': '6606c2d.png',
              'title': 'Abduzeedo Design Inspiration | Design Inspiration '
                       '& Tutorials',
              'url': 'http://abduzeedo.com'},
  '788824e': {'is_public': True,
              'tags': ['Design'],
              'thumb': '788824e.png',
              'title': 'Dribbble - Show and tell for designers',
              'url': 'https://dribbble.com'},
  '8d8c1ae': {'is_public': True,
              'tags': ['Design', 'UX'],
              'thumb': '8d8c1ae.png',
              'title': 'Little Big Details - Your daily dose of design '
                       'inspiration',
              'url': 'http://littlebigdetails.com'},
  'c673adf': {'is_public': True,
              'tags': ['UX'],
              'thumb': 'c673adf.png',
              'title': 'Why ‘Sign Up’ and ‘Sign In’ Button Labels Confuse '
                       'Users - UX Movement',
              'url': 'http://uxmovement.com/buttons/why-sign-up-and-sign-in-button-labels-confuse-users/'},
  'caacb2a': {'is_public': True,
              'tags': ['Design'],
              'thumb': 'caacb2a.png',
              'title': 'UX Archive',
              'url': 'http://www.uxarchive.com'},
  'd809b5d': {'is_public': True,
              'tags': ['Design'],
              'thumb': 'd809b5d.png',
              'title': 'Behance',
              'url': 'http://www.behance.net'},
  'dd66a81': {'is_public': True,
              'tags': ['Design'],
              'thumb': 'dd66a81.png',
              'title': 'Dribbble - Email_App_big.png by Sanadas young',
              'url': 'http://dribbble.com/shots/1191804-Email-App/attachments/157598'},
  'ded8921': {'is_public': True,
              'tags': ['Design', 'Colors'],
              'thumb': 'ded8921.png',
              'title': 'Adobe Color CC',
              'url': 'http://kuler.adobe.com/explore/'}}]